// Design tokens extracted from design/stitch-export/archive_intelligence/DESIGN.md and the
// per-screen code.html exports. Shared across all 4 pages so the palette/type scale stays in
// sync in one place instead of being copy-pasted 4x.
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1b1b",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1c1c16",
        "secondary-container": "#e6dfd4",
        "primary-fixed-dim": "#a9c7ff",
        "on-primary": "#ffffff",
        "primary-container": "#002b5b",
        "surface-container": "#f0eded",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-fixed": "#1e1b15",
        "on-secondary-container": "#67625a",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#cdc5bc",
        error: "#ba1a1a",
        secondary: "#635e56",
        "on-primary-fixed-variant": "#264778",
        "tertiary-fixed": "#e6e2d9",
        "tertiary-fixed-dim": "#cac6be",
        primary: "#001736",
        outline: "#747780",
        "on-error": "#ffffff",
        "secondary-fixed": "#e9e1d7",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#a9c7ff",
        "on-surface": "#1c1b1b",
        "on-primary-container": "#7594ca",
        "surface-bright": "#fcf9f8",
        "tertiary-container": "#2d2c26",
        "surface-dim": "#dcd9d9",
        tertiary: "#181812",
        "on-tertiary-container": "#96938b",
        "primary-fixed": "#d6e3ff",
        "outline-variant": "#c4c6d0",
        "on-primary-fixed": "#001b3d",
        "surface-tint": "#405f91",
        "surface-container-high": "#eae7e7",
        "error-container": "#ffdad6",
        background: "#fcf9f8",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#484740",
        "on-secondary-fixed-variant": "#4a463f",
        "surface-variant": "#e5e2e1",
        surface: "#fcf9f8",
        "on-surface-variant": "#43474f",
        "surface-container-low": "#f6f3f2",
        "inverse-surface": "#313030",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "container-padding": "24px",
        "sidebar-width": "260px",
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        gutter: "1px",
      },
      fontFamily: {
        "body-sm": ["Hanken Grotesk"],
        "display-lg": ['"Source Serif 4"'],
        "data-mono": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
        "body-lg": ["Hanken Grotesk"],
        "headline-sm": ['"Source Serif 4"'],
        "headline-md": ['"Source Serif 4"'],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["42px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "450" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
};
